version: "3.6"

services:
  backend:
    image: scholarship-backend
    container_name: "scholarship-backend-onest"
    restart: always
    ports:
      - 9004:3000
    env_file:
      - ./.env
  #refer env https://piramal-swasthya.gitbook.io/uba/toasters/beneficiary-toaster/developer-guide/backend-guide/build-and-deploy-steps#example-.env-for-docker file for below environment variables
   postgres:
    image: postgres:14.17
    #container_name: strapi-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - strapi_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - strapi_nw

  pgadmin:
    image: dpage/pgadmin4:latest
    #container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8082:80"
    networks:
      - strapi_nw

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    #container_name: keycloak
    restart: unless-stopped
    command: ["start-dev"]
    environment:
      KC_DB: ${KC_DB}
      KC_DB_URL: ${KC_DB_URL}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_URL: http://localhost:8080
      KC_HOSTNAME_ADMIN_URL: http://localhost:8080
      KEYCLOAK_FRONTEND_URL: http://localhost:8080
      KC_HOSTNAME_STRICT: "false"
      PROXY_ADDRESS_FORWARDING: "true"
    volumes:
      - ./keycloak-import:/opt/keycloak/data/import
    ports:
      - 8080:8080
    networks:
      - strapi_nw
    depends_on:
      - postgres

  # Hasura service
  hasura:
    image: hasura/graphql-engine
    #container_name: Hasura-Dev
    ports:
      - "8081:8080"
    environment:
      - HASURA_GRAPHQL_DATABASE_URL=${HASURA_GRAPHQL_DATABASE_URL}
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
      - HASURA_GRAPHQL_ENABLED_LOG_TYPES=startup, http-log, webhook-log, websocket-log, query-log
      - HASURA_GRAPHQL_ADMIN_SECRET=${HASURA_GRAPHQL_ADMIN_SECRET}

    volumes:
      - ./metadata:/hasura-metadata
      - ./migrations:/hasura-migrations
    networks:
      - strapi_nw
    depends_on:
      - postgres
      
  

volumes:
  strapi_pg_data:
  strapi_node_modules:
  strapi_build:
  strapi_npm_cache:

networks:
  strapi_nw:
    name: strapi
    driver: bridge
