version: "3.3"

services:
  beneficiary-backend:
    image: beneficiary-backend:latest
    restart: unless-stopped
    container_name: beneficiary-backend
    ports:
      - 3000:3000
    env_file:
      - ./.env
