name: Deploy to Server

on:
  push:
    branches:
      - '*'  # Trigger on any branch push

jobs:
  Deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    environment: UBA-DEV

    steps:
      - name: Deploy Stack via SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.HOST_NAME }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            # ----- Export variables -----
            export BASE_DIR="${{ secrets.TARGET_DIR }}"
            export BRANCH="${GITHUB_REF#refs/heads/}"  # Extract branch name
            export SERVICE_NAME="beneficiary-backend"

            # ----- Change to project directory -----
            cd "$BASE_DIR" || exit 1

            # ----- Prepare .env -----
            if [ -f .env ]; then rm .env; fi
            echo "${{ secrets.SERVER_ENV }}" > .env

            # ----- Ensure deploy.sh is executable -----
            chmod +x deploy.sh

            # ----- Run deploy script -----
            ./deploy.sh

      - name: Notify on Slack
        uses: iRoachie/slack-github-actions@v2.3.2
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
        if: ${{ always() }}
